INSERT INTO university.department (code, name) VALUES
('CS', 'Computer Science'),
('ENG', 'Engineering'),
('BIO', 'Biology'),
('CHE', 'Chemistry'),
('PHY', 'Physics'),
('CLA', 'Liberal Arts'),
('MUS', 'Music'),
('ART', 'Art'),
('EDU', 'Education'),
('MATH', 'Mathematics')
ON CONFLICT (code) DO NOTHING;

INSERT INTO university.instructor (dept_id, first_name, last_name, email) VALUES
(1, 'Alice', 'Reyes', 'alice.reyes@univ.edu'), -- ins_id 1
(1, 'Bob', 'Tan', 'bob.tan@univ.edu'), -- ins_id 2
(2, 'Clara', 'Dela Cruz', 'clara@univ.edu'),
(2, 'David', 'Lim', 'david.lim@univ.edu'),
(3, 'Eva', 'Garcia', 'eva.garcia@univ.edu'),
(4, 'Frank', 'Wong', 'frank.wong@univ.edu'),
(5, 'Grace', 'Nguyen', 'grace.nguyen@univ.edu'),
(6, 'Hannah', 'Lee', 'hannah.lee@univ.edu'),
(7, 'Ian', 'Martinez', 'ian.martinez@univ.edu'),
(8, 'Jasmine', 'Lopez', 'jasmine.lopez@univ.edu'),
(9, 'Kevin', 'Hernandez', 'kevin.hernandez@univ.edu'),
(10, 'Lily', 'Gonzalez', 'lily.gonzalez@univ.edu'),
(1, 'Michael', 'Smith', 'michael.smith@univ.edu'), -- ins_id 13
(2, 'Nina', 'Johnson', 'nina.johnson@univ.edu'),
(3, 'Oscar', 'Brown', 'oscar.brown@univ.edu'),
(4, 'Paula', 'Davis', 'paula.davis@univ.edu'),
(5, 'Quinn', 'Miller', 'quinn.miller@univ.edu'),
(6, 'Rachel', 'Wilson', 'rachel.wilson@univ.edu'),
(7, 'Sam', 'Moore', 'sam.moore@univ.edu'),
(8, 'Tina', 'Taylor', 'tina.taylor@univ.edu'),
(9, 'Uma', 'Anderson', 'uma.anderson@univ.edu'),
(10, 'Victor', 'Thomas', 'victor.thomas@univ.edu'),
(1, 'Wendy', 'Jackson', 'wendy.jackson@univ.edu'), -- ins_id 23
(2, 'Xander', 'White', 'xander.white@univ.edu'),
(3, 'Yara', 'Harris', 'yara.harris@univ.edu'),
(4, 'Zane', 'Martin', 'zane.martin@univ.edu'),
(5, 'Aaron', 'Thompson', 'aaron.thompson@univ.edu'),
(6, 'Bella', 'Scott', 'bella.scott@univ.edu'),
(7, 'Carlos', 'Adams', 'carlos.adams@univ.edu'),
(8, 'Diana', 'Nelson', 'diana.nelson@univ.edu'),
(9, 'Ethan', 'Carter', 'ethan.carter@univ.edu'),
(10, 'Fiona', 'Mitchell', 'fiona.mitchell@univ.edu'),
(1, 'George', 'Perez', 'george.perez@univ.edu'),
(2, 'Hailey', 'Roberts', 'hailey.roberts@univ.edu'),
(3, 'Isaac', 'Turner', 'isaac.turner@univ.edu'),
(4, 'Jocelyn', 'Phillips', 'jocelyn.phillips@univ.edu'),
(5, 'Kyle', 'Campbell', 'kyle.campbell@univ.edu'),
(6, 'Laura', 'Parker', 'laura.parker@univ.edu'),
(7, 'Mason', 'Evans', 'mason.evans@univ.edu'),
(8, 'Nora', 'Edwards', 'nora.edwards@univ.edu'),
(9, 'Owen', 'Collins', 'owen.collins@univ.edu'),
(10, 'Penelope', 'Stewart', 'penelope.stewart@univ.edu'),
(1, 'Quentin', 'Sanchez', 'quentin.sanchez@univ.edu'),
(2, 'Riley', 'Morris', 'riley.morris@univ.edu'),
(3, 'Sophia', 'Rogers', 'sophia.rogers@univ.edu'),
(4, 'Tristan', 'Cook', 'tristan.cook@univ.edu'),
(5, 'Ursula', 'Murphy', 'ursula.murphy@univ.edu'),
(6, 'Victor', 'Bailey', 'victor.bailey@univ.edu'),
(7, 'Willow', 'Rivera', 'willow.rivera@univ.edu'),
(8, 'Xavier', 'Cooper', 'xavier.cooper@univ.edu'),
(9, 'Yvonne', 'Richardson', 'yvonne.richardson@univ.edu'),
(10, 'Zachary', 'Howard', 'zachary.howard@univ.edu'),
(1, 'Ariana', 'Ward', 'ariana.ward@univ.edu'),
(2, 'Benjamin', 'Brooks', 'benjamin.brooks@univ.edu'),
(3, 'Caitlyn', 'Gray', 'caitlyn.gray@univ.edu'),
(4, 'Derrick', 'Watson', 'derrick.watson@univ.edu'),
(5, 'Elena', 'James', 'elena.james@univ.edu')
ON CONFLICT (email) DO NOTHING;

INSERT INTO university.student (student_number, first_name, last_name, email) VALUES
('S1001', 'Julian', 'Briones', 'julian.briones@univ.edu'),
('S1002', 'Ella', 'Dela Cruz', 'ella.dela.cruz@univ.edu'),
('S1003', 'Mark', 'Villanueva', 'mark.villanueva@univ.edu'),
('S1004', 'Sophia', 'Garcia', 'sophia.garcia@univ.edu'),
('S1005', 'Liam', 'Reyes', 'liam.reyes@univ.edu'),
('S1006', 'Olivia', 'Tan', 'olivia.tan@univ.edu'),
('S1007', 'Noah', 'Davis', 'noah.davis@univ.edu'),
('S1008', 'Ava', 'Martinez', 'ava.martinez@univ.edu'),
('S1009', 'Elijah', 'Hernandez', 'elijah.hernandez@univ.edu'),
('S1010', 'Isabella', 'Lopez', 'isabella.lopez@univ.edu'),
('S1011', 'James', 'Gonzalez', 'james.gonzalez@univ.edu'),
('S1012', 'Mia', 'Wilson', 'mia.wilson@univ.edu'),
('S1013', 'Benjamin', 'Anderson', 'benjamin.anderson@univ.edu'),
('S1014', 'Charlotte', 'Thomas', 'charlotte.thomas@univ.edu'),
('S1015', 'Lucas', 'Moore', 'lucas.moore@univ.edu'),
('S1016', 'Amelia', 'Taylor', 'amelia.taylor@univ.edu'),
('S1017', 'Mason', 'Jackson', 'mason.jackson@univ.edu'),
('S1018', 'Harper', 'White', 'harper.white@univ.edu'),
('S1019', 'Ethan', 'Harris', 'ethan.harris@univ.edu'),
('S1020', 'Evelyn', 'Martin', 'evelyn.martin@univ.edu'),
('S1021', 'Alexander', 'Thompson', 'alexander.thompson@univ.edu'),
('S1022', 'Sofia', 'Scott', 'sofia.scott@univ.edu'),
('S1023', 'Henry', 'Adams', 'henry.adams@univ.edu'),
('S1024', 'Ella', 'Nelson', 'ella.nelson@univ.edu'),
('S1025', 'Jacob', 'Carter', 'jacob.carter@univ.edu'),
('S1026', 'Scarlett', 'Mitchell', 'scarlett.mitchell@univ.edu'),
('S1027', 'Michael', 'Perez', 'michael.perez@univ.edu'),
('S1028', 'Aria', 'Roberts', 'aria.roberts@univ.edu'),
('S1029', 'Daniel', 'Turner', 'daniel.turner@univ.edu'),
('S1030', 'Luna', 'Phillips', 'luna.phillips@univ.edu'),
('S1031', 'Matthew', 'Campbell', 'matthew.campbell@univ.edu'),
('S1032', 'Zoe', 'Parker', 'zoe.parker@univ.edu'),
('S1033', 'Joseph', 'Evans', 'joseph.evans@univ.edu'),
('S1034', 'Lily', 'Edwards', 'lily.edwards@univ.edu'),
('S1035', 'Samuel', 'Collins', 'samuel.collins@univ.edu'),
('S1036', 'Hannah', 'Stewart', 'hannah.stewart@univ.edu'),
('S1037', 'David', 'Sanchez', 'david.sanchez@univ.edu'),
('S1038', 'Grace', 'Morris', 'grace.morris@univ.edu'),
('S1039', 'Carter', 'Rogers', 'carter.rogers@univ.edu'),
('S1040', 'Chloe', 'Cook', 'chloe.cook@univ.edu'),
('S1041', 'Owen', 'Murphy', 'owen.murphy@univ.edu'),
('S1042', 'Penelope', 'Bailey', 'penelope.bailey@univ.edu'),
('S1043', 'Wyatt', 'Rivera', 'wyatt.rivera@univ.edu'),
('S1044', 'Lillian', 'Cooper', 'lillian.cooper@univ.edu'),
('S1045', 'Jack', 'Richardson', 'jack.richardson@univ.edu'),
('S1046', 'Nora', 'Howard', 'nora.howard@univ.edu'),
('S1047', 'Luke', 'Ward', 'luke.ward@univ.edu'),
('S1048', 'Zara', 'Brooks', 'zara.brooks@univ.edu'),
('S1049', 'Gabriel', 'Gray', 'gabriel.gray@univ.edu'),
('S1050', 'Violet', 'Watson', 'violet.watson@univ.edu'),
('S1051', 'Cameron', 'James', 'cameron.james@univ.edu'),
('S1052', 'Aurora', 'Scott', 'aurora.scott@univ.edu'),
('S1053', 'Eli', 'Adams', 'eli.adams@univ.edu'),
('S1054', 'Savannah', 'Nelson', 'savannah.nelson@univ.edu'),
('S1055', 'Isaiah', 'Carter', 'isaiah.carter@univ.edu'),
('S1056', 'Audrey', 'Mitchell', 'audrey.mitchell@univ.edu'),
('S1057', 'Anthony', 'Perez', 'anthony.perez@univ.edu'),
('S1058', 'Brooklyn', 'Roberts', 'brooklyn.roberts@univ.edu'),
('S1059', 'Thomas', 'Turner', 'thomas.turner@univ.edu'),
('S1060', 'Claire', 'Phillips', 'claire.phillips@univ.edu'),
('S1061', 'Charles', 'Campbell', 'charles.campbell@univ.edu'),
('S1062', 'Skylar', 'Parker', 'skylar.parker@univ.edu'),
('S1063', 'Josiah', 'Evans', 'josiah.evans@univ.edu'),
('S1064', 'Genesis', 'Edwards', 'genesis.edwards@univ.edu'),
('S1065', 'Hudson', 'Collins', 'hudson.collins@univ.edu'),
('S1066', 'Aaliyah', 'Stewart', 'aaliyah.stewart@univ.edu'),
('S1067', 'Lincoln', 'Sanchez', 'lincoln.sanchez@univ.edu'),
('S1068', 'Madelyn', 'Morris', 'madelyn.morris@univ.edu'),
('S1069', 'Nathan', 'Rogers', 'nathan.rogers@univ.edu'),
('S1070', 'Ruby', 'Cook', 'ruby.cook@univ.edu'),
('S1071', 'Caleb', 'Murphy', 'caleb.murphy@univ.edu'),
('S1072', 'Serenity', 'Bailey', 'serenity.bailey@univ.edu'),
('S1073', 'Ryan', 'Rivera', 'ryan.rivera@univ.edu'),
('S1074', 'Eva', 'Cooper', 'eva.cooper@univ.edu'),
('S1075', 'Adrian', 'Richardson', 'adrian.richardson@univ.edu'),
('S1076', 'Autumn', 'Howard', 'autumn.howard@univ.edu'),
('S1077', 'Christian', 'Ward', 'christian.ward@univ.edu'),
('S1078', 'Hailey', 'Brooks', 'hailey.brooks@univ.edu'),
('S1079', 'Ezekiel', 'Gray', 'ezekiel.gray@univ.edu'),
('S1080', 'Alice', 'Watson', 'alice.watson@univ.edu'),
('S1081', 'Colton', 'James', 'colton.james@univ.edu'),
('S1082', 'Anna', 'Scott', 'anna.scott@univ.edu'),
('S1083', 'Jordan', 'Adams', 'jordan.adams@univ.edu'),
('S1084', 'Vivian', 'Nelson', 'vivian.nelson@univ.edu'),
('S1085', 'Brayden', 'Carter', 'brayden.carter@univ.edu'),
('S1086', 'Kennedy', 'Mitchell', 'kennedy.mitchell@univ.edu'),
('S1087', 'Ian', 'Perez', 'ian.perez@univ.edu'),
('S1088', 'Sadie', 'Roberts', 'sadie.roberts@univ.edu'),
('S1089', 'Austin', 'Turner', 'austin.turner@univ.edu'),
('S1090', 'Peyton', 'Phillips', 'peyton.phillips@univ.edu'),
('S1091', 'Jordan', 'Campbell', 'jordan.campbell@univ.edu'),
('S1092', 'Clara', 'Parker', 'clara.parker@univ.edu'),
('S1093', 'Adam', 'Evans', 'adam.evans@univ.edu'),
('S1094', 'Ariana', 'Edwards', 'ariana.edwards@univ.edu'),
('S1095', 'Evan', 'Collins', 'evan.collins@univ.edu'),
('S1096', 'Liliana', 'Stewart', 'liliana.stewart@univ.edu'),
('S1097', 'Jason', 'Sanchez', 'jason.sanchez@univ.edu'),
('S1098', 'Maria', 'Morris', 'maria.morris@univ.edu'),
('S1099', 'Cole', 'Rogers', 'cole.rogers@univ.edu'),
('S1100', 'Kinsley', 'Cook', 'kinsley.cook@univ.edu')
ON CONFLICT (student_number) DO NOTHING;

-- still need to add courses and sections
INSERT INTO university.course (dept_id, code, title, credits) VALUES
(1,'CS101','Intro to Programming',3.0),
(1,'CS102','Data Structures',3.0),
(1,'CS201','Algorithms',3.0),
(1,'CS202','Computer Architecture',3.0),
(1,'CS301','Operating Systems',3.0),

(2,'ENG101','Statics',3.0),
(2,'ENG102','Dynamics',3.0),
(2,'ENG201','Thermodynamics',3.0),
(2,'ENG202','Fluid Mechanics',3.0),
(2,'ENG301','Engineering Materials',3.0),

(3,'BIO101','General Biology',3.0),
(3,'BIO102','Cell Biology',3.0),
(3,'BIO201','Genetics',3.0),
(3,'BIO202','Microbiology',3.0),
(3,'BIO301','Molecular Biology',3.0),

(4,'CHE101','General Chemistry',3.0),
(4,'CHE102','Organic Chemistry',3.0),
(4,'CHE201','Physical Chemistry',3.0),
(4,'CHE202','Analytical Chemistry',3.0),
(4,'CHE301','Biochemistry',3.0),

(5,'PHY101','Classical Mechanics',3.0),
(5,'PHY102','Electromagnetism',3.0),
(5,'PHY201','Quantum Physics',3.0),
(5,'PHY202','Thermodynamics',3.0),
(5,'PHY301','Optics',3.0),

(6,'CLA101','World Literature',3.0),
(6,'CLA102','Creative Writing',3.0),
(6,'CLA201','Philosophy',3.0),
(6,'CLA202','Ethics',3.0),
(6,'CLA301','Humanities Seminar',3.0),

(7,'MUS101','Music Theory',3.0),
(7,'MUS102','Music History',3.0),
(7,'MUS201','Composition',3.0),
(7,'MUS202','Conducting',3.0),
(7,'MUS301','Advanced Performance',3.0),

(8,'ART101','Drawing I',3.0),
(8,'ART102','Painting I',3.0),
(8,'ART201','Sculpture',3.0),
(8,'ART202','Digital Arts',3.0),
(8,'ART301','Advanced Studio',3.0),

(9,'EDU101','Foundations of Education',3.0),
(9,'EDU102','Educational Psychology',3.0),
(9,'EDU201','Assessment of Learning',3.0),
(9,'EDU202','Curriculum Development',3.0),
(9,'EDU301','Teaching Strategies',3.0),

(10,'MATH101','College Algebra',3.0),
(10,'MATH102','Trigonometry',3.0),
(10,'MATH201','Calculus I',3.0),
(10,'MATH202','Calculus II',3.0),
(10,'MATH301','Linear Algebra',3.0)
ON CONFLICT (dept_id, code) DO NOTHING;

INSERT INTO university.section (course_id, section_code, instructor_id, capacity) VALUES
-- Dept: CS Intro to Programming Sections
(1, 'A', 1, 40),
(1, 'B', 1, 40),
(1, 'C', 2, 40),
(1, 'D', 2, 40),
-- Data Structures Sections
(2, 'A', 1, 35),
(2, 'B', 1, 35),
(2, 'C', 2, 35),
(2, 'D', 2, 35),
-- Algorithms Sections
(3, 'A', 13, 40),
(3, 'B', 13, 40),
(3, 'C', 23, 40),
(3, 'D', 23, 40),
-- Computer Architecture Sections
(4, 'A', 1, 25),
(4, 'B', 2, 25),
(4, 'C', 13, 25),
(4, 'D', 23, 25),
-- Operating Systems Sections
(5, 'A', 13, 25),
(5, 'B', 13, 25),
(5, 'C', 23, 25),
(5, 'D', 23, 25)
ON CONFLICT (course_id, section_code) DO NOTHING;